# Generated by Django 4.0.2 on 2022-05-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20210422_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='sentiment_predicted',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
    ]
