# Generated by Django 4.0.2 on 2022-05-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_review_sentiment_predicted'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sentiment_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
