# Generated by Django 4.0.2 on 2022-05-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_product_sentiment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='sarcasm_detected',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=13, null=True),
        ),
    ]
